import { useState, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { toast } from 'react-hot-toast'
import { generateReadme } from '../api/client'
import { generateReadmeDocumentationPdf } from '../utils/generateReportPdf'

export default function ReadmeModal({ sessionId, repoName, open, onClose }) {
  const [readme, setReadme] = useState('')
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [pdfLoading, setPdfLoading] = useState(false)
  const previewRef = useRef(null)

  // Auto-fetch when opened
  if (open && !readme && !loading) {
    setLoading(true)
    generateReadme(sessionId).then((res) => {
      setReadme(res.readme || '')
      setLoading(false)
    }).catch(() => {
      setReadme('# Error\nFailed to generate README. Please check your API key.')
      setLoading(false)
    })
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(readme)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([readme], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'README.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleGeneratePdf = async () => {
    if (!previewRef.current || !readme.trim()) {
      toast.error('Documentation is not ready yet')
      return
    }
    setPdfLoading(true)
    const t = toast.loading('Building PDF…')
    try {
      await generateReadmeDocumentationPdf({
        element: previewRef.current,
        repoName: repoName || undefined,
      })
      toast.success('PDF downloaded', { id: t })
    } catch (e) {
      console.error(e)
      toast.error(e?.message || 'Could not generate PDF', { id: t })
    } finally {
      setPdfLoading(false)
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 2000,
          background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(10px)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
        }}>
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            style={{
              width: '100%', maxWidth: 1000, height: '90vh',
              background: 'var(--bg-card)',
              border: '1px solid var(--border)',
              borderRadius: 24,
              display: 'flex', flexDirection: 'column',
              overflow: 'hidden',
              boxShadow: '0 50px 100px -20px rgba(0,0,0,0.5)',
            }}
          >
            {/* Header */}
            <div style={{
              padding: '20px 24px', borderBottom: '1px solid var(--border)',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              background: 'rgba(255,255,255,0.02)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <div style={{ fontSize: 24 }}>📄</div>
                <div>
                  <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700 }}>AI Professional README</h2>
                  <p style={{ margin: 0, fontSize: 12, color: 'var(--text-muted)' }}>Generated by Groq LLM</p>
                </div>
              </div>
              <div style={{ display: 'flex', gap: 10 }}>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleCopy}
                  style={{
                    padding: '8px 16px', borderRadius: 12,
                    background: 'rgba(255,255,255,0.05)',
                    border: '1px solid var(--border)', color: 'white', fontWeight: 600, fontSize: 13,
                    cursor: 'pointer',
                  }}
                >
                  {copied ? '✅ Copied' : '📋 Copy'}
                </motion.button>
                <motion.button
                  whileHover={{ scale: pdfLoading ? 1 : 1.05 }}
                  whileTap={{ scale: pdfLoading ? 1 : 0.95 }}
                  onClick={handleGeneratePdf}
                  disabled={loading || !readme.trim() || pdfLoading}
                  style={{
                    padding: '8px 16px', borderRadius: 12,
                    background: 'linear-gradient(135deg, #7c3aed, #3b82f6)',
                    border: 'none', color: 'white', fontWeight: 600, fontSize: 13,
                    cursor: loading || !readme.trim() || pdfLoading ? 'not-allowed' : 'pointer',
                    display: 'flex', alignItems: 'center', gap: 8,
                    opacity: loading || !readme.trim() || pdfLoading ? 0.6 : 1,
                  }}
                >
                  {pdfLoading ? '⏳ PDF…' : '📄 Generate PDF'}
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleDownload}
                  style={{
                    padding: '8px 16px', borderRadius: 12,
                    background: 'linear-gradient(135deg, #10b981, #059669)',
                    border: 'none', color: 'white', fontWeight: 600, fontSize: 13,
                    cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8,
                  }}
                >
                  📥 Download .md
                </motion.button>
                <button
                  onClick={onClose}
                  style={{
                    width: 36, height: 36, borderRadius: '50%',
                    background: 'rgba(255,255,255,0.05)', border: 'none',
                    color: 'var(--text-muted)', cursor: 'pointer', fontSize: 20,
                  }}
                >
                  ×
                </button>
              </div>
            </div>

            {/* Content Preview */}
            <div
              ref={previewRef}
              className="readme-preview"
              style={{
              flex: 1, overflowY: 'auto', padding: '40px',
              color: '#e6edf3', lineHeight: 1.6,
              background: '#0d1117', // GitHub dark theme background
            }}
            >
              <style>{`
                .readme-preview h1 { border-bottom: 1px solid #30363d; padding-bottom: 0.3em; margin-bottom: 24px; font-size: 2em; }
                .readme-preview h2 { border-bottom: 1px solid #30363d; padding-bottom: 0.3em; margin-top: 24px; margin-bottom: 16px; font-weight: 600; line-height: 1.25; }
                .readme-preview p { margin-bottom: 16px; }
                .readme-preview code { padding: 0.2em 0.4em; margin: 0; font-size: 85%; background: rgba(110,118,129,0.4); borderRadius: 6px; }
                .readme-preview pre { padding: 16px; overflow: auto; font-size: 85%; line-height: 1.45; background: #161b22; borderRadius: 6px; margin-bottom: 16px; border: 1px solid #30363d; }
                .readme-preview ul { padding-left: 2em; margin-bottom: 16px; }
                .readme-preview li { margin-bottom: 4px; }
                .readme-preview blockquote { padding: 0 1em; color: #8b949e; border-left: 0.25em solid #30363d; margin-bottom: 16px; }
              `}</style>
              
              {loading ? (
                <div style={{ textAlign: 'center', marginTop: 40 }}>
                   <div className="shimmer" style={{ height: 40, width: '80%', margin: '0 auto 20px', borderRadius: 8 }} />
                   <div className="shimmer" style={{ height: 20, width: '60%', margin: '0 auto 10px', borderRadius: 8 }} />
                   <div className="shimmer" style={{ height: 20, width: '40%', margin: '0 auto 10px', borderRadius: 8 }} />
                </div>
              ) : (
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {readme}
                </ReactMarkdown>
              )}
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
